# 監視間隔(分で指定)
# TODO 必要に応じて変更する
monitor_interval_minutes: 1
# 停止時間 低: 負荷高, 信憑性高 / 高: 負荷低, 信憑性低
sleep_time: 1
# ログフォルダ名
# TODO 必要に応じて変更する
log_folder: "../../ログ"
# 設備名
# TODO 変更する
facility_name: 'facility_A'
# CSVの定義
csv_columns:
  date: 日付
  time: 時刻
  man-hour: 実作業有無
  machine_time: マシンタイム
  active_window_title: アクティブなウィンドウの名前

# モニタリング対象のプロセス
# TODO 変更する
monitoring_process:
  # 監視したいアプリケーション名
  names:
    - Visual Studio Code
    - Teams


