# 監視間隔(分で指定)
monitor_interval_minutes: 5
# ログフォルダ名
log_folder: "./logs"
# 設備名
facility_name: 'facility_A'
# CSVの定義
csv_columns:
  date: 日付
  time: 時刻
  facility_operation_status: 稼働状況
# モニタリング対象のプロセス
# - プロセス名はタスクマネージャ上でプロセスの「プロパティ」を選択することで見ることが出来る
# - CPU負荷のしきい値はプロセス名と対応する位置に記述する
# 例
  # names:
  #   - Taskmgr.exe
  #   - QaseeClient.exe
  # cpu_usage_thresholds:
  #   - 3.0
  #   - 0.1
monitored_processes:
  # 監視したいプロセス名
  names:
    - Taskmgr.exe
    - QaseeClient.exe
  # 稼働判定とするCPU負荷のしきい値
  cpu_usage_thresholds:
    - 3.0
    - 0.1


