# 監視間隔(分で指定)
monitor_interval_minutes: 5
# ログフォルダ名
log_folder: "./test/fixtures/duplication_exist"
# 設備名
facility_name: 'facility_A'
# CSVの定義
csv_columns:
  data: 日付
  time: 時刻
  existence_of_input: 入力有無
  cpu_usage: CPU負荷[%]
  # モニタリング対象のプロセス
  # monitored_process:

